### ISSUE TITLE
Demo Cleanup Issue

### ISSUE THREAD

**Issue by mickey-octodemo** [mickeygoussetorg/intro-to-github-actions-talk#3]
Track cleaning up the demos that currently exist

- [x] Demo 01
- [x] Demo 02
- [x] Demo 03
- [x] Demo 04
- [x] Remove Demo 05
- [x] Make Demo 06 => Demo 05
- [x] Create Demo 06 - Using an LFIX Bulb
- [x] Write up demo 05 MD file
- [x] Write up demo 06 MD file
- [x] Add a tag so you can reset the repo to a beginning state.
- [x] Create tag to be able to reset repo

**Comment by mickey-octodemo** [comment]
Does slack update if I add this comment

**Comment by mickeygousset** [comment]
git reset --hard v1
git push --force

Resets the demo environment. 

If I make permanent changes to the demo environment, I'll need to update the tag appropriately.
